zstd image transport plugin
ros-perception/image_transport_plugins pull request #154
Opened 2023-09-27 09:04 UTC by ahcorde

zstd image transport plugin

2024-01-18 02:21 UTC, ijnek requested changes
@ahcorde First of all, I apologise for the super long delay in getting this reviewed. Thank you for this addition. The changes look solid, and I have tested it and they work great (and it's fast!).

I have two minor request for changes, and I think otherwise everything looks good.
I had a look at the CI, and I don't see any tests failing (but rather some errors like):

```
03:10:45 [GNU C Compiler (gcc)] [-ERROR-] - '/tmp/ws/src/image_transport_plugins/zstd_image_transport/src/zlib_cpp.cpp', IO exception has been thrown: java.nio.file.NoSuchFileException: /tmp/ws/src/image_transport_plugins/zstd_image_transport/src/zlib_cpp.cpp
03:10:45 [GNU C Compiler (gcc)] [-ERROR-] - '/tmp/ws/src/image_transport_plugins/zstd_image_transport/src/zlib_cpp.cpp', IO exception has been thrown: java.nio.file.NoSuchFileException: /tmp/ws/src/image_transport_plugins/zstd_image_transport/src/zlib_cpp.cpp
03:10:45 [GNU C Compiler (gcc)] [-ERROR-] - '/tmp/ws/src/image_transport_plugins/zstd_image_transport/src/zlib_cpp.cpp', IO exception has been thrown: java.nio.file.NoSuchFileException: /tmp/ws/src/image_transport_plugins/zstd_image_transport/src/zlib_cpp.cpp
```
I've seen them infrequently show up on the buildfarm, but not quite sure what the problem is.

2024-01-18 02:21 UTC, ijnek commented on zstd_image_transport/CMakeLists.txt
> +find_package(sensor_msgs REQUIRED)
```suggestion
find_package(sensor_msgs REQUIRED)
find_package(ZLIB REQUIRED)
```

2024-01-18 02:21 UTC, ijnek commented on zstd_image_transport/CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME})
```suggestion
target_link_libraries(${PROJECT_NAME} ZLIB::ZLIB)
```

2024-01-18 02:21 UTC, ijnek commented on zstd_image_transport/package.xml
> +  <depend>image_transport</depend>
```suggestion
  <depend>image_transport</depend>
  <depend>zlib</depend>
```

2024-01-18 02:21 UTC, ijnek commented on zstd_image_transport/src/zlib_cpp.cpp
> +        return std::move(out_data_list);
``warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]``
Let the compiler do return value optimization instead by not using move semantics.

```suggestion
        return out_data_list;
```

2024-01-18 02:21 UTC, ijnek commented on zstd_image_transport/src/zlib_cpp.cpp
> +        return std::move(out_data_list);
```suggestion
        return out_data_list;
```

2024-01-18 02:21 UTC, ijnek commented on zstd_image_transport/src/zlib_cpp.cpp
> +  return std::move(out_data_list);
```suggestion
  return out_data_list;
```

2024-01-18 02:21 UTC, ijnek commented on zstd_image_transport/src/zstd_publisher.cpp
> +  // transport scoped parameter (e.g. image_raw.compressed.format)
```suggestion
  // transport scoped parameter (e.g. image_raw.zstd.zstd_level)
```

2024-01-18 13:00 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=20094)](http://ci.ros2.org/job/ci_linux/20094/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14541)](http://ci.ros2.org/job/ci_linux-aarch64/14541/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20814)](http://ci.ros2.org/job/ci_windows/20814/)

2024-01-18 23:11 UTC, ijnek approved these changes

2024-01-18 23:11 UTC, merged

2024-02-11 15:44 UTC, authaldo commented
Small question regarding the new plugin: 
Has the `<exec_depend>zstd_image_transport</exec_depend>` within the package.xml of the metapackage been omitted on purpose?

2024-02-12 09:32 UTC, ahcorde commented
@authaldo I forgot to include it. PR https://github.com/ros-perception/image_transport_plugins/pull/162