Added common linters to theora_image_transport
ros-perception/image_transport_plugins pull request #169
Opened 2024-07-29 11:31 UTC by ahcorde

2024-07-29 11:51 UTC, clalancette requested changes

2024-07-29 11:51 UTC, clalancette commented on theora_image_transport/src/ogg_saver.cpp
> +    fout_.write(static_cast<char *>(page.body, page.body_len));
```suggestion
    fout_.write(static_cast<char *>(page.header), page.header_len);
    fout_.write(static_cast<char *>(page.body), page.body_len);
```

2024-07-30 10:33 UTC, ahcorde commented
friendly ping @clalancette

2024-07-30 12:19 UTC, clalancette approved these changes

2024-07-30 12:28 UTC, merged